import { Message, JupyterNotebook, NotebookCell } from "../types";
import { AGENTS } from "../constants";

export const convertToIpynb = (messages: Message[]): JupyterNotebook => {
  const cells: NotebookCell[] = [];

  // Add an initial header cell
  cells.push({
    cell_type: 'markdown',
    metadata: {},
    source: [
      "# Grandmaster AI Team Solution\n",
      "Generated by autonomous AI agents.\n",
      "---\n"
    ],
    execution_count: null,
    outputs: []
  });

  messages.forEach(msg => {
    if (msg.agentId === 'user') {
      cells.push({
        cell_type: 'markdown',
        metadata: {},
        source: [`## User Request\n\n${msg.content}`],
        execution_count: null,
        outputs: []
      });
      return;
    }

    const agent = AGENTS.find(a => a.id === msg.agentId);
    const agentName = agent ? agent.name : 'Unknown Agent';

    // Split content by code blocks
    const parts = msg.content.split(/(```python[\s\S]*?```)/g);

    // Header for the agent's turn
    cells.push({
      cell_type: 'markdown',
      metadata: {},
      source: [`### 🤖 ${agentName} (${agent?.role})\n`],
      execution_count: null,
      outputs: []
    });

    parts.forEach(part => {
      if (part.startsWith('```python')) {
        // Extract code
        const code = part.replace(/^```python\n/, '').replace(/```$/, '');
        // Split into lines for Jupyter format
        const sourceLines = code.split('\n').map(line => line + '\n');
        
        cells.push({
          cell_type: 'code',
          metadata: {},
          source: sourceLines,
          execution_count: null,
          outputs: []
        });
      } else if (part.trim().length > 0) {
        // Markdown text
        cells.push({
          cell_type: 'markdown',
          metadata: {},
          source: [part],
          execution_count: null,
          outputs: []
        });
      }
    });
  });

  return {
    cells,
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3"
      },
      language_info: {
        codemirror_mode: {
          name: "ipython",
          version: 3
        },
        file_extension: ".py",
        mimetype: "text/x-python",
        name: "python",
        nbconvert_exporter: "python",
        pygments_lexer: "ipython3",
        version: "3.8.5"
      }
    },
    nbformat: 4,
    nbformat_minor: 4
  };
};

export const downloadNotebook = (notebook: JupyterNotebook, filename: string = 'solution.ipynb') => {
  const blob = new Blob([JSON.stringify(notebook, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
